name: Babashka-based unit tests
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          bb: latest

      - run: ./test_runner.clj
