name: CLJS unit tests
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: 1.12.0.1530

      - name: Cache dependencies
        uses: actions/cache@v4.2.3
        env:
          cache-name: cache-clj
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --prefer-offline

      - run: clojure -M:oli-test:full-stack-deps
