name: JVM unit tests
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.0.1488

      - name: Cache dependencies
        uses: actions/cache@v4.1.2
        env:
          cache-name: cache-clj
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-


      - run: ./bin/kaocha unit
