name: Clj-kondo linting
on: push
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        clj-kondo: '2023.07.13'

    - name: Lint
      run: clj-kondo --lint src:test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
